### ISSUE TITLE
OSlash dependency is not meant for production use

### ISSUE THREAD

**Issue by mikepii** [explodinglabs/jsonrpcserver#225]
jsonrpcserver uses the [OSlash](https://github.com/dbrattli/OSlash) package. From the [OSlash readme](https://github.com/dbrattli/OSlash/blob/c271c7633daf9d72393b419cfc9229e427e6a42a/README.md):

> OSlash is intended to be a tutorial. For practical functional programming in Python in production environments you should use Expression instead.

**Comment by bcb** [comment]
Yes I’m keen to remove the dependency. One issue we found is that there’s no conda recipe for OSlash which in turn means no jsonrpcserver in conda.

We should use some other library or even write a simple bind function to include in jsonrpcserver. That’s the only part of OSlash being used.

**Comment by bcb** [comment]
I just found https://github.com/dry-python/returns which would be perfect for this.

**Comment by bcb** [comment]
This has been merged into version 6, which is coming soon.

**Comment by antispam2002** [comment]
Any chances to get v6 out soon?

**Comment by bcb** [comment]
Yeah, all that’s left for 6 is to replace setup.py with pyproject.toml and some documentation and then I’ll make a pre-release.
