### ISSUE TITLE
"Result" monad's "Left" and "Right" types are reversed

### ISSUE THREAD

**Issue by mikepii** [explodinglabs/jsonrpcserver#226]
`Result` is defined as:

https://github.com/explodinglabs/jsonrpcserver/blob/f489ed886f68b893ec95c38297ea84c5df2c5adb/jsonrpcserver/result.py#L34

However, the runtime values are reversed:

https://github.com/explodinglabs/jsonrpcserver/blob/f489ed886f68b893ec95c38297ea84c5df2c5adb/jsonrpcserver/dispatcher.py#L105-L114

Therefore mypy complains if users type their methods with `-> Result`.

**Comment by bcb** [comment]
Are you able to send a PR for this?

**Comment by bcb** [comment]
Otherwise I can do it later today. 

Thanks for reporting by the way.

**Comment by mikepii** [comment]
sure, I'll send a PR
