### ISSUE TITLE
Support for custom parameters' validators

### ISSUE THREAD

**Issue by antispam2002** [explodinglabs/jsonrpcserver#234]
Currently, the parameters' validation is bound to
```
    try:
        signature(func).bind(*extract_args(request, context), **extract_kwargs(request))
    except TypeError as exc:
        return Left(InvalidParamsResult(str(exc)))
    return Right(func)
```
in [dispatcher.py](https://github.com/explodinglabs/jsonrpcserver/blob/cbc8e39ae968ed439dafa5e6e0619f2ccaa0a8f1/jsonrpcserver/dispatcher.py#L141)

This validation checks if the method's signature is compatible with provided parameters. However, there is no easy way to interfere in this validation, e.g. to provide own error messages, etc.

Would be very nice to have a way to specify some custom parameters' validation callable/class/etc when annotating a method with @method decorator.

**Comment by bcb** [comment]
Yes - great idea. I will actually add this this week, for version 6.

**Comment by bcb** [comment]
Added to version 6
