### ISSUE TITLE
Blocking task with status callbacks

### ISSUE THREAD

**Issue by lolsborn** [explodinglabs/jsonrpcserver#263]
I am trying to have an RPC method that will create a resource an on success return a response with the correct rpc id.  In the meantime I want it to send status notifications for that resource based on a callback provided by a third-party library.

Here is a minimal example:
https://gist.github.com/lolsborn/2a4e00a64c830a43a7ccbdd554f39831

The issue I'm having is the callback method is not async, but I need to call websocket.send() which is asynchronous.  I've tried a lot of ways to get this to work, but have been stuck for sometime and would appreciate any insights you might have.

**Comment by bcb** [comment]
Hi @lolsborn (keep in mind I am not an asyncio expert) - any reason blocking_with_callback can't be async? I had success with your code once that was made async.
