### ISSUE TITLE
Option to dispatch async methods in order

### ISSUE THREAD

**Issue by uSpike** [explodinglabs/jsonrpcserver#75]
JSON-RPC 2.0 spec says:
> The Server MAY process a batch rpc call as a set of concurrent tasks, processing them in any order and with any width of parallelism.

It would be useful to me for the ability to run the async dispatcher optionally in order of requests, instead of in parallel.  My changes would be something like:

```python
async def call_requests(
    requests: Union[Request, Iterable[Request]], methods: Methods, ordered: bool, debug: bool
) -> Response:
    if isinstance(requests, collections.Iterable):
        if ordered:
            responses = [await safe_call(r, methods, debug=debug) for r in requests]
            return BatchResponse(responses)
        else:
            responses = (safe_call(r, methods, debug=debug) for r in requests)
            return BatchResponse(await asyncio.gather(*responses))
    return await safe_call(requests, methods, debug=debug)
```
and `create_requests` would need to return a `list` instead of a `set` so that requests are ordered.

If you think this is a useful feature, I'd be happy to submit a PR.

Thanks!

**Comment by bcb** [comment]
Sounds good, send it through.

**Comment by bcb** [comment]
@uSpike couldn't you use the synchronous server for this?

**Comment by uSpike** [comment]
@bcb I could, but there's still the issue that `create_requests` makes a `set` (non-ordered) instead of a `list`.  Additionally, I'd have to wrap the synchronous dispatch in a `ThreadPoolExecutor` since my application is async.

It may end up easier for me to do this on my own and integrate different dispatchers with different methods.

**Comment by bcb** [comment]
Happy to change it to a list.

**Comment by bcb** [comment]
I believe this should no longer be a problem, use regular dispatch instead of the asynchronous one.
